@url = http://localhost:5000/conferences-module 
@hostId = 5d5d5c87-9b3d-4fc5-9d84-c1a6e0550154
@conferenceId = 4f1207bc-2df3-4ad0-84b7-fae88e3e518c

###
GET {{url}}

###
GET {{url}}/hosts

###
GET {{url}}/hosts/{{hostId}}

###
POST {{url}}/hosts
Content-Type: application/json

{
    "Name": "Host",
    "Description": "Lorem Ipsum"
}

###
PUT {{url}}/hosts/{{hostId}}
Content-Type: application/json

{
    "Name": "Host 1",
    "Description": "Lorem Ipsum 1"
}

###
DELETE {{url}}/hosts/{{hostId}}


###
GET {{url}}/conferences

###
GET {{url}}/conferences/{{conferenceId}}

###
POST {{url}}/conferences
Content-Type: application/json

{
    "HostId": "{{hostId}}",
    "Name": "Conference",
    "Description": "Lorem Ipsum",
    "Location": "Almaty",
    "From": "2022-11-01",
    "To": "2022-11-02"
}

###
PUT {{url}}/conferences/{{conferenceId}}
Content-Type: application/json

{
    "HostId": "{{hostId}}",
    "Name": "Conference 2",
    "Description": "Lorem Ipsum 2",
    "Location": "Almaty lol",
    "From": "2022-09-01",
    "To": "2022-09-02"
}

###
DELETE {{url}}/conferences/{{conferenceId}}